In [1]:
import numpy as np
a=np.array([10,20,30,40,50])
print(a)
print(type(a))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [5]:
b=np.array(([1,2],[3,4],[5,6]))
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
c=np.array([7,8,9],dtype=float)
print(c)
print(type(c))

[7. 8. 9.]
<class 'numpy.ndarray'>


In [9]:
d=np.zeros(6)
print(d)
e=np.ones((3,2),dtype=int)
print(e)

[0. 0. 0. 0. 0. 0.]
[[1 1]
 [1 1]
 [1 1]]


In [10]:
f=np.empty((2,2))
print(f)

[[0.00000000e+000 1.30534142e-311]
 [1.30534143e-311 1.30534142e-311]]


In [11]:
g=np.arange(0,20,2)
print(g)
print(np.linspace(0,1,6))

[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.2 0.4 0.6 0.8 1. ]


In [13]:
print(np.random.random((3,3)))

[[0.70351808 0.04690577 0.85123011]
 [0.58434861 0.12703088 0.03555231]
 [0.36792152 0.59547173 0.45938155]]
