In [10]:
import numpy as np
arr=np.arange(0,21,1)
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
(21,)
21
int64


In [8]:
np.random.seed(1)
arr=np.random.randint(10,size=(4,5))
print(arr)
print(arr.size)
print(arr.nbytes)

[[5 8 9 5 0]
 [0 1 7 6 9]
 [2 4 5 2 4]
 [2 4 7 7 9]]
20
80


In [42]:
np.random.seed(1)
arr=np.arange(1,13).reshape(3,4)
print(arr)
print(arr[1,])
print(arr[:,2])
print(arr[-1,])
print(arr[2,])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]
[ 3  7 11]
[ 9 10 11 12]
[ 9 10 11 12]


In [40]:
np.random.seed(1)
arr=np.random.randint(10,size=(3,4))
print(arr)
print(arr[:2,:2])


[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]
[[5 8]
 [0 0]]
[[8 5]
 [0 7]
 [9 4]]
[[5 9 8 5]
 [7 1 0 0]
 [4 2 9 6]]
